### ISSUE TITLE
对2020祭祖II的补充

### ISSUE THREAD

**Issue by ZCWzy** [LevickCG/Happy-SE-in-XDU#2]
第一题：某总线的时钟频率是100Mhz，数据线是16位，一个内存读写总线周期由4个时钟周期完成。在该总线上实现00000H--07FFFH的内存区域，需要8K*4的SRAM共多少片？若该SRAM的存储周期为50ns，请分析它是否能满足该总线的速度要求，给出理由

第二题：第7章书上课后习题第31题，数据都没变

第三题：貌似是给了书上P287的图，问是哪种方式

第七题：8259的固定优先级是如何安排的？若8259中IR1的中断向量号是49H，则IR6的中断向量号是？

大题第一个：
类似第六章第五题

八路组相连的那个题:
计算机Cache与内存采⽤8路组相联⽅式映射，Cache容量为16KB，Cache组内每块1KB；内存容量1MB。
问：1.内存区号、区内组号、组内块号、块内地址号各多少位表示； 
2. 设当前地址变换表如下，地址变换表分组顺序排列（第1⾏对应第0组第0块，第2⾏对应第0组第1块…），求0xABCDEH变换后Cache地址。

//等我今年考了再补寄网和数据库和编译原理

**Comment by LevickCG** [comment]
> 第一题：某总线的时钟频率是100Mhz，数据线是16位，一个内存读写总线周期由4个时钟周期完成。在该总线上实现00000H--07FFFH的内存区域，需要8K*4的SRAM共多少片？若该SRAM的存储周期为50ns，请分析它是否能满足该总线的速度要求，给出理由
> 
> 第二题：第7章书上课后习题第31题，数据都没变
> 
> 第三题：貌似是给了书上P287的图，问是哪种方式
> 
> 第七题：8259的固定优先级是如何安排的？若8259中IR1的中断向量号是49H，则IR6的中断向量号是？
> 
> 大题第一个： 类似第六章第五题
> 
> 八路组相连的那个题: 计算机Cache与内存采⽤8路组相联⽅式映射，Cache容量为16KB，Cache组内每块1KB；内存容量1MB。 问：1.内存区号、区内组号、组内块号、块内地址号各多少位表示； 2. 设当前地址变换表如下，地址变换表分组顺序排列（第1⾏对应第0组第0块，第2⾏对应第0组第1块…），求0xABCDEH变换后Cache地址。
> 
> //等我今年考了再补寄网和数据库和编译原理

可以直接pull request 我加到相应的文件夹中。
