### ISSUE TITLE
斗胆求一下Glonee学长的联系方式，谢谢QAQ

### ISSUE THREAD

**Issue by Avery-zzZ** [LevickCG/Happy-SE-in-XDU#5]
在[/OS/2021OSfinal.md](https://github.com/LevickCG/Happy-SE-in-XDU/blob/master/OS/2021OSfinal.md)中提到有打印店卖20期末试题

> ## PS：打印店的题目是真的 ##

我找了3家打印店，都没有卖，最新都是15年的

希望能得到Glonee学长指点，**感谢** orz

**Comment by Avery-zzZ** [comment]
chenquanns@gmail.com

**Comment by LevickCG** [comment]
可以去他仓库提issue问问，我没有他的联系方式。

**Comment by Avery-zzZ** [comment]
感谢

**Comment by Glonee** [comment]
@Avery-zzZ 其实你当时可以直接艾特我的。。。

**Comment by Avery-zzZ** [comment]
当时还不知道可以@ 😿
